## smartcard-reset.playbook.yml
## Install and startup the USB smartcard failure bodge.
## USAGE:
---
- name: 'Install fix for yubikey not being detected until reinserted'
  hosts: localhost
  become: root
  vars:
    # User who the smartcard must work for.
    sc_user: "sandia" 
  tasks:
  - name: 'Install service to auto-reset smartcards'
    ansible.builtin.include_tasks:
      file: 'smartcard-reset-service.tasks.yml'
    # vars:
    #   sc_user: "sandia" # User who service targets.
    #   uninstall: yes # Service gets removed if uninstall is defined and true.
